### ISSUE TITLE
無法Enable Eden

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#1]
[19:45:11 ERROR]: Error occurred while enabling Eden v1.0-BETA-8bfc470 (Is it up to date?)
java.lang.NoClassDefFoundError: org/imanity/imanityspigot/movement/MovementHandler
        at rip.diamond.practice.Eden.loadGeneral(Eden.java:191) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.imanity.imanityspigot.movement.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 13 more
[19:45:11 INFO]: [Eden] Disabling Eden v1.0-BETA-8bfc470

使用的是Paper Spigot 1.8.8
不知為何無法開啟
個人猜想可能是這問題
Caused by: java.lang.ClassNotFoundException: org.imanity.imanityspigot.movement.MovementHandler

**Comment by RealGoodestEnglish** [comment]
能否發一下整個Server 開啟時候的Log 嗎?

**Comment by Zhuyuan0907** [comment]
> 能否發一下整個Server 開啟時候的Log 嗎?

Loading libraries, please wait...
[10:31:50 INFO]: Starting minecraft server version 1.8.8
[10:31:50 INFO]: Loading properties
[10:31:50 INFO]: Default game type: SURVIVAL
[10:31:51 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[10:31:51 INFO]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[10:31:51 INFO]: Server Ping Player Sample Count: 12
[10:31:51 INFO]: Using 4 threads for Netty based IO
[10:31:51 INFO]: Debug logging is disabled
[10:31:51 INFO]: Data value allowed items: 
[10:31:51 INFO]: Generating keypair
[10:31:51 INFO]: Starting Minecraft server on 0.0.0.0:30002
[10:31:51 INFO]: Using epoll channel type
[10:31:51 INFO]: Set PluginClassLoader as parallel capable
[10:31:51 INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v21.03.26-5ff3a9b-1286-22.3.9
[10:31:51 INFO]: [ViaVersion] Loading ViaVersion v4.3.1
[10:31:51 INFO]: [ViaVersion] ViaVersion 4.3.1 is now loaded, injecting!
[10:31:51 INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[10:31:52 INFO]: [ViaVersion] Loading block connection mappings ...
[10:31:52 INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[10:31:52 INFO]: [ViaVersion] Loading 1.18 -> 1.19 mappings...
[10:31:52 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[10:31:53 INFO]: [LuckPerms] Loading LuckPerms v5.4.40
[10:31:54 INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[10:31:54 INFO]: [Eden] Loading Eden v1.0-BETA-8bfc470
[10:31:54 INFO]: [LiteBans] Loading LiteBans v2.8.13
[10:31:54 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v21.03.26-5ff3a9b-1286-22.3.9
[10:31:54 WARN]: SLF4J: No SLF4J providers were found.
[10:31:54 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[10:31:54 WARN]: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[10:31:54 INFO]: Vault is used for persistent `/wea` toggles.
[10:31:55 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[10:31:55 INFO]: [ProtocolLib] Started structure compiler thread.
[10:31:55 INFO]: [LuckPerms] Enabling LuckPerms v5.4.40
[10:31:55 INFO]:         __    
[10:31:55 INFO]:   |    |__)   LuckPerms v5.4.40
[10:31:55 INFO]:   |___ |      Running on Bukkit - CraftBukkit
[10:31:55 INFO]: 
[10:31:55 INFO]: [LuckPerms] Loading configuration...
[10:31:55 INFO]: [LuckPerms] Loading storage provider... [H2]
[10:31:56 INFO]: [LuckPerms] Loading internal permission managers...
[10:31:56 INFO]: [LuckPerms] Performing initial data load...
[10:31:57 INFO]: [LuckPerms] Successfully enabled. (took 1696ms)
[10:31:57 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[10:31:57 INFO]: Preparing level "world"
[10:31:57 INFO]: -------- World Settings For [world] --------
[10:31:57 INFO]: Mob Spawn Range: 4
[10:31:57 INFO]: Nerfing mobs spawned from spawners: false
[10:31:57 INFO]: Anti X-Ray: true
[10:31:57 INFO]:        Engine Mode: 1
[10:31:57 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:31:57 INFO]:        Replace Blocks: [1, 5]
[10:31:57 INFO]: Cactus Growth Modifier: 100%
[10:31:57 INFO]: Cane Growth Modifier: 100%
[10:31:57 INFO]: Melon Growth Modifier: 100%
[10:31:57 INFO]: Mushroom Growth Modifier: 100%
[10:31:57 INFO]: Pumpkin Growth Modifier: 100%
[10:31:57 INFO]: Sapling Growth Modifier: 100%
[10:31:57 INFO]: Wheat Growth Modifier: 100%
[10:31:57 INFO]: NetherWart Growth Modifier: 100%
[10:31:57 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:31:57 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:31:57 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:31:57 INFO]: Random Lighting Updates: false
[10:31:57 INFO]: Structure Info Saving: true
[10:31:57 INFO]: Sending up to 10 chunks per packet
[10:31:57 INFO]: Max Entity Collisions: 8
[10:31:57 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:31:57 INFO]: Max TNT Explosions: 100
[10:31:57 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:31:57 INFO]: Item Despawn Rate: 6000
[10:31:57 INFO]: Item Merge Radius: 2.5
[10:31:57 INFO]: Arrow Despawn Rate: 1200
[10:31:57 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:31:57 INFO]: View Distance: 10
[10:31:57 INFO]: Zombie Aggressive Towards Villager: true
[10:31:57 INFO]: Chunks to Grow per Tick: 650
[10:31:57 INFO]: Clear tick list: false
[10:31:57 INFO]: Experience Merge Radius: 3.0
[10:31:57 INFO]: -------- World Settings For [world] --------
[10:31:57 INFO]: Remove invalid mob spawner tile entities: true
[10:31:57 INFO]: Player blocking damage multiplier set to 0.5
[10:31:57 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:31:57 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:31:57 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[10:31:57 INFO]: Water over lava flow speed: 5
[10:31:57 INFO]: Fix TNT cannons: false
[10:31:57 INFO]: Allow undead horse types to be leashed: false
[10:31:57 INFO]: Keep spawn chunk loaded: true
[10:31:57 INFO]: WorldServer TickNextTick cap set at 10000
[10:31:57 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:31:57 INFO]: World async lighting: false
[10:31:57 INFO]: -------- World Settings For [world_nether] --------
[10:31:57 INFO]: Mob Spawn Range: 4
[10:31:57 INFO]: Nerfing mobs spawned from spawners: false
[10:31:57 INFO]: Anti X-Ray: true
[10:31:57 INFO]:        Engine Mode: 1
[10:31:57 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:31:57 INFO]:        Replace Blocks: [1, 5]
[10:31:57 INFO]: Cactus Growth Modifier: 100%
[10:31:57 INFO]: Cane Growth Modifier: 100%
[10:31:57 INFO]: Melon Growth Modifier: 100%
[10:31:57 INFO]: Mushroom Growth Modifier: 100%
[10:31:57 INFO]: Pumpkin Growth Modifier: 100%
[10:31:57 INFO]: Sapling Growth Modifier: 100%
[10:31:57 INFO]: Wheat Growth Modifier: 100%
[10:31:57 INFO]: NetherWart Growth Modifier: 100%
[10:31:57 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:31:57 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:31:57 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:31:57 INFO]: Random Lighting Updates: false
[10:31:57 INFO]: Structure Info Saving: true
[10:31:57 INFO]: Sending up to 10 chunks per packet
[10:31:57 INFO]: Max Entity Collisions: 8
[10:31:57 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:31:57 INFO]: Max TNT Explosions: 100
[10:31:57 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:31:57 INFO]: Item Despawn Rate: 6000
[10:31:57 INFO]: Item Merge Radius: 2.5
[10:31:57 INFO]: Arrow Despawn Rate: 1200
[10:31:57 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:31:57 INFO]: View Distance: 10
[10:31:57 INFO]: Zombie Aggressive Towards Villager: true
[10:31:57 INFO]: Chunks to Grow per Tick: 650
[10:31:57 INFO]: Clear tick list: false
[10:31:57 INFO]: Experience Merge Radius: 3.0
[10:31:57 INFO]: -------- World Settings For [world_nether] --------
[10:31:57 INFO]: Remove invalid mob spawner tile entities: true
[10:31:57 INFO]: Player blocking damage multiplier set to 0.5
[10:31:57 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:31:57 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:31:57 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[10:31:57 INFO]: Water over lava flow speed: 5
[10:31:57 INFO]: Fix TNT cannons: false
[10:31:57 INFO]: Allow undead horse types to be leashed: false
[10:31:57 INFO]: Keep spawn chunk loaded: true
[10:31:57 INFO]: WorldServer TickNextTick cap set at 10000
[10:31:57 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:31:57 INFO]: World async lighting: false
[10:31:57 INFO]: -------- World Settings For [world_the_end] --------
[10:31:57 INFO]: Mob Spawn Range: 4
[10:31:57 INFO]: Nerfing mobs spawned from spawners: false
[10:31:57 INFO]: Anti X-Ray: true
[10:31:57 INFO]:        Engine Mode: 1
[10:31:57 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[10:31:57 INFO]:        Replace Blocks: [1, 5]
[10:31:57 INFO]: Cactus Growth Modifier: 100%
[10:31:57 INFO]: Cane Growth Modifier: 100%
[10:31:57 INFO]: Melon Growth Modifier: 100%
[10:31:57 INFO]: Mushroom Growth Modifier: 100%
[10:31:57 INFO]: Pumpkin Growth Modifier: 100%
[10:31:57 INFO]: Sapling Growth Modifier: 100%
[10:31:57 INFO]: Wheat Growth Modifier: 100%
[10:31:57 INFO]: NetherWart Growth Modifier: 100%
[10:31:57 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:31:57 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:31:57 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:31:57 INFO]: Random Lighting Updates: false
[10:31:57 INFO]: Structure Info Saving: true
[10:31:57 INFO]: Sending up to 10 chunks per packet
[10:31:57 INFO]: Max Entity Collisions: 8
[10:31:57 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[10:31:57 INFO]: Max TNT Explosions: 100
[10:31:57 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:31:57 INFO]: Item Despawn Rate: 6000
[10:31:57 INFO]: Item Merge Radius: 2.5
[10:31:57 INFO]: Arrow Despawn Rate: 1200
[10:31:57 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:31:57 INFO]: View Distance: 10
[10:31:57 INFO]: Zombie Aggressive Towards Villager: true
[10:31:57 INFO]: Chunks to Grow per Tick: 650
[10:31:57 INFO]: Clear tick list: false
[10:31:57 INFO]: Experience Merge Radius: 3.0
[10:31:57 INFO]: -------- World Settings For [world_the_end] --------
[10:31:57 INFO]: Remove invalid mob spawner tile entities: true
[10:31:57 INFO]: Player blocking damage multiplier set to 0.5
[10:31:57 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[10:31:57 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[10:31:57 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[10:31:57 INFO]: Water over lava flow speed: 5
[10:31:57 INFO]: Fix TNT cannons: false
[10:31:57 INFO]: Allow undead horse types to be leashed: false
[10:31:57 INFO]: Keep spawn chunk loaded: true
[10:31:57 INFO]: WorldServer TickNextTick cap set at 10000
[10:31:57 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[10:31:57 INFO]: World async lighting: false
[10:31:57 INFO]: Preparing start region for level 0 (Seed: -2426861938189152298)
[10:31:58 INFO]: Preparing spawn area: 17%
[10:31:59 INFO]: Preparing start region for level 1 (Seed: -2426861938189152298)
[10:31:59 INFO]: Preparing start region for level 2 (Seed: -2426861938189152298)
[10:31:59 INFO]: [ViaVersion] Enabling ViaVersion v4.3.1
[10:31:59 INFO]: [WorldEdit] Enabling WorldEdit v6.1.7;dd00bb1
[10:31:59 INFO]: WEPIF: Using the Bukkit Permissions API.
[10:32:00 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[10:32:00 INFO]: [Eden] Enabling Eden v1.0-BETA-8bfc470
[10:32:00 WARN]: SLF4J not found on the classpath.  Logging is disabled for the 'org.mongodb.driver' component
[10:32:00 INFO]: [LOG] Cannot find the custom spigot, vanilla knockback will be applied
[10:32:00 ERROR]: Error occurred while enabling Eden v1.0-BETA-8bfc470 (Is it up to date?)
java.lang.NoClassDefFoundError: org/imanity/imanityspigot/movement/MovementHandler
        at rip.diamond.practice.Eden.loadGeneral(Eden.java:191) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: org.imanity.imanityspigot.movement.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 13 more
[10:32:00 INFO]: [Eden] Disabling Eden v1.0-BETA-8bfc470
[10:32:00 INFO]: [LiteBans] Enabling LiteBans v2.8.13
[10:32:01 INFO]: [LiteBans] Loading SQL driver: h2 1.4.197 (org.h2.Driver)
[10:32:01 INFO]: [LiteBans] Connecting to database...
[10:32:01 INFO]: [LiteBans] litebans-pool - Starting...
[10:32:01 INFO]: [LiteBans] litebans-pool - Start completed.
[10:32:01 INFO]: [LiteBans] Connected to H2 database successfully (555.6 ms).
[10:32:01 INFO]: [LiteBans] Database connection fully initialized (560 ms).
[10:32:01 INFO]: [LiteBans] v2.8.13 enabled. Startup took 661 ms.
[10:32:01 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:32:02 INFO]: Done (4.984s)! For help, type "help" or "?"
CheapServer控制台: Server marked as running...
[10:32:02 INFO]: Timings Reset
[10:32:02 INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x (47)
[10:32:02 WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
[10:32:02 WARN]: [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 1.8.0_312). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[10:32:02 INFO]: (FAWE) Detected class org.bukkit.event.block.BlockExplodeEvent
[10:32:02 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[10:32:03 WARN]: [ViaVersion] There is a newer plugin version available: 4.4.2, you're on: 4.3.1

**Comment by RealGoodestEnglish** [comment]
請先試一試使用最新的[版本](https://github.com/RealGoodestEnglish/Eden/releases/tag/1.0.1-BETA-8639ac2), 如果還是無法使用的話請告訴我, 並且再使用pastebin 貼上後台Log

**Comment by Zhuyuan0907** [comment]
> 

https://pastebin.com/bDY37FBG

**Comment by RealGoodestEnglish** [comment]
pastebin 的還是在使用舊版本

**Comment by Zhuyuan0907** [comment]
我有點找到問題點了
你說我還是用舊版本
但我明明就是安裝最新版本
但Log卻顯示說我安裝的是1.0-BETA-8bfc470
我剛剛去Eden-1.0.1-BETA-8639ac2-all_2.jar他的plugin.yml看了一下
發現你好像沒有改到

最新版本(BETA-8639ac2-all_2)他的plugin.yml是長這樣子的

main: rip.diamond.practice.Eden
name: Eden
version: 1.0-BETA-8bfc470
author: GoodestEnglish
description: The best free practice plugin with premium features
website: https://youtube.com/c/goodestenglishpvp

所以...可能不是我沒安裝最新版本~
但我還是不知道為甚麼LOG會出現錯誤就是了

**Comment by Zhuyuan0907** [comment]
> 我有點找到問題點了 你說我還是用舊版本 但我明明就是安裝最新版本 但Log卻顯示說我安裝的是1.0-BETA-8bfc470 我剛剛去Eden-1.0.1-BETA-8639ac2-all_2.jar他的plugin.yml看了一下 發現你好像沒有改到
> 
> 最新版本(BETA-8639ac2-all_2)他的plugin.yml是長這樣子的
> 
> main: rip.diamond.practice.Eden name: Eden version: 1.0-BETA-8bfc470 author: GoodestEnglish description: The best free practice plugin with premium features website: https://youtube.com/c/goodestenglishpvp
> 
> 所以...可能不是我沒安裝最新版本~ 但我還是不知道為甚麼LOG會出現錯誤就是了

**Comment by RealGoodestEnglish** [comment]
請嘗試使用這個版本 https://github.com/RealGoodestEnglish/Eden/releases/tag/1.0.2-BETA-d3b45cf
如果還有問題, 請再通知我

**Comment by Zhuyuan0907** [comment]
不好意思麻煩您這麼多w
那目前我找到了一些bug

首先是玩家加入時
[09:27:05 INFO]: UUID of player Zhuyuan_0907 is 4a752c5c-c6b3-4bdb-aec4-23674ce9b491
[09:27:05 ERROR]: Could not pass event PlayerJoinEvent to Eden v1.0.2-BETA-d3b45cf
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:557) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at rip.diamond.practice.util.Util.teleport(Util.java:289) ~[?:?]
        at rip.diamond.practice.profile.listener.ProfileListener.onJoin(ProfileListener.java:47) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more

"[09:27:05 ERROR]: Could not pass event PlayerJoinEvent to Eden v1.0.2-BETA-d3b45cf"
沒有辦法找到PlayerJoinEvent

並且不管在server中打任何指令
ex:/help /plugins /verison /gamemode /give
都會顯示說
[Eden] System is loading your profile... Please wait for a few seconds.
我嘗試放著讓它加載看看
但都無動於衷
目前是發現這個bug 謝謝:)

**Comment by Zhuyuan0907** [comment]
[12:15:37 INFO]: UUID of player Zhuyuan_0907 is 4a752c5c-c6b3-4bdb-aec4-23674ce9b491
[12:15:38 INFO]: Zhuyuan_0907[/25.21.182.40:36734] logged in with entity id 13 at ([world]-23.36741697025325, 35.0, -1725.1503213897633)
[12:15:38 WARN]: a Lag Spike has been detected! Timestamp: 2022-10-14_12-15-38, last tick time: 125.56ms
[12:15:38 WARN]: java.lang.NullPointerException
[12:15:38 WARN]:        at rip.diamond.practice.profile.PlayerProfile.fromBson(PlayerProfile.java:67)
[12:15:38 WARN]:        at rip.diamond.practice.profile.PlayerProfile.lambda$load$2(PlayerProfile.java:169)
[12:15:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[12:15:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[12:15:38 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[12:15:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:15:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:15:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:15:38 WARN]: a Lag Spike has been detected! Timestamp: 2022-10-14_12-15-38, last tick time: 409.81ms
[12:15:38 INFO]: Zhuyuan_0907 lost connection: [Eden] Unable to load your data. Please try to re-login in a few seconds
[12:15:38 WARN]: handleDisconnection() called twice
[12:15:38 WARN]: a Lag Spike has been detected! Timestamp: 2022-10-14_12-15-38, last tick time: 230.01ms

當前spigot已轉為iSpigot 3 Premium版
這次錯誤是在我設定完場地 我重開伺服器時
一重新啟動完 就無法登入伺服器
一直顯示"[Eden] Unable to load your data. Please try to re-login in a few seconds"
不知為何會這樣(?
