### ISSUE TITLE
加载时出现问题

### ISSUE THREAD

**Issue by Xiro0419** [RealGoodestEnglish/Eden#3]
[21:53:09 INFO]: [Eden] Enabling Eden v1.0-BETA-8bfc470
[21:53:09 WARN]: SLF4J not found on the classpath.  Logging is disabled for the 'org.mongodb.driver' component
[21:53:10 INFO]: [LOG] Cannot find the custom spigot, vanilla knockback will be applied
[21:53:10 ERROR]: Error occurred while enabling Eden v1.0-BETA-8bfc470 (Is it up to date?)
java.lang.NoClassDefFoundError: org/imanity/imanityspigot/movement/MovementHandler
        at rip.diamond.practice.Eden.loadGeneral(Eden.java:191) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:106) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: org.imanity.imanityspigot.movement.MovementHandler
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        ... 13 more
[21:53:10 INFO]: [Eden] Disabling Eden v1.0-BETA-8bfc470

版本：PaperSpigot 1.8.8

Config.yml
## Developer option, set to false if GoodestEnglish didn't tell you to set to true
debug: false
## MongoDB login information
mongo:
  uri-mode: true
  normal:
    host: 127.0.0.1
    port: 27017
    auth:
      enabled: false
      username: ''
      password: ''
  uri:
    database: Practice
    connection-string: mongodb://127.0.0.1:27017/Practice
## Toggle if the fancy tablist should be enabled or not
fancy-tablist: true
nametag:
  ## Toggle if the plugin should modify the nametag color or not
  enabled: true
  ## What color should the nametag be when the player is in lobby?
  ## Check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html for available colors
  color: BLUE
party:
  ## When player creates a party, what is the default size?
  default-max-size: 30
lobby:
  ## Should player allow to see other players?
  display-players: false
match:
  ## If points are enabled, how many points should it be?
  maximum-points: 3
  goal-portal-protect-radius: 3
  ## Right now boxing will count hit as 2 hits if player is spam clicking and jumping (critical hits)
  ## This option will change paperspigot's config 'disable-player-crits' to true. So crit hit will not be exists anymore.
  ## Warning: This option will disable crit damage, and will change and save paperspigot's 'disable-player-crits' settings
  fix-hit-count-error: true
## Simple chat format
chat-format:
  ## Set this to true if you want to enable chat format
  enabled: true
  ## What is the format should be? (This supports PlaceholderAPI)
  ## Use %1$s for player's name and %2$s for player's message
  format: "&a%1$s&f: %2$s"
## If you are not using, then turn every imanity related settings off
imanity:
  teleport-async: false

**Comment by RealGoodestEnglish** [comment]
跟 #1 重複了, 請查看 https://github.com/RealGoodestEnglish/Eden/issues/1#issuecomment-1275271124
