### ISSUE TITLE
CarbonSpigot Error

### ISSUE THREAD

**Issue by Zhuyuan0907** [RealGoodestEnglish/Eden#7]
[06:06:07 INFO]: [LOG] 偵測到伺服器正在運行 CARBON_SPIGOT, 擊退運作將會使用這個伺服器核心
[06:06:07 INFO]: [PlaceholderAPI] Successfully registered expansion: eden [1.0.7-BETA-51954a7]
[06:06:07 INFO]: [LOG] Loaded 1 house arenas
[06:06:07 INFO]: [LOG] Loaded 1 Mansion arenas
[06:06:07 INFO]: [LOG] Loaded 1 Rocky arenas
[06:06:07 INFO]: [LOG] Loaded 1 farmland arenas
[06:06:07 INFO]: [LOG] Loaded 1 Purple arenas
[06:06:07 INFO]: [LOG] Loaded 1 Christmas arenas
[06:06:07 INFO]: [LOG] Loaded 1 Pokemon arenas
[06:06:07 INFO]: [LOG] Loaded 1 bridge arenas
[06:06:07 ERROR]: Error occurred while enabling Eden v1.0.7-BETA-51954a7 (Is it up to date?)
java.lang.NoClassDefFoundError: xyz/refinedev/spigot/api/handlers/impl/MovementHandler
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_312]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_312]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at rip.diamond.practice.movement.MovementHandler.<init>(MovementHandler.java:19) ~[?:?]
        at rip.diamond.practice.movement.impl.MatchMovementHandler.<init>(MatchMovementHandler.java:20) ~[?:?]
        at rip.diamond.practice.Eden.loadGeneral(Eden.java:195) ~[?:?]
        at rip.diamond.practice.Eden.onEnable(Eden.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:329) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:410) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:374) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:329) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:296) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:569) [CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: xyz.refinedev.spigot.api.handlers.impl.MovementHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CarbonSpigot.jar:git-CarbonSpigot-Server-e022e84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 30 more
[06:06:07 INFO]: [Eden] Disabling Eden v1.0.7-BETA-51954a7

Can't enable the CarbonSpigot.

**Comment by RealGoodestEnglish** [comment]
請問你使用的 CarbonSpigot版本是什麼?

**Comment by Zhuyuan0907** [comment]
> 請問你使用的 CarbonSpigot版本是什麼?

2.0 Ver.

**Comment by RealGoodestEnglish** [comment]
> > 請問你使用的 CarbonSpigot版本是什麼?
> 
> 2.0 Ver.

嘗試使用 3.2.2, 因為Eden 正在使用3.2.2版本的API, 我不知道舊版本的API跟新版本的API會不會有不同
